baseURL = 'https://brozorec.github.io/'
languageCode = 'en-us'
title = "Boyan Barakov's Blog"
theme = 'github.com/adityatelange/hugo-PaperMod'

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
            [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)'], ['$', '$']]

[params]
    math = true
    defaultTheme = "auto"
    ShareButtons = ["reddit", "telegram", "linkedin", "x"]
    ShowShareButtons = true
    #ShowBreadCrumbs = true

    [params.label]
        text = "Home"
    [params.assets]
        favicon = "/favicon.ico"
    [params.homeInfoParams]
        Title =  "Boyan Barakov"
        Content = "Blockchain developer, building open source at @OpenZeppelin"
    [[params.socialIcons]]
        name = "GitHub"
        url = "https://github.com/brozorec"
    [[params.socialIcons]]
        name = "X"
        url = "https://x.com/BoyanBarakov"
    [[params.socialIcons]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/boyan-barakov-3b91891a"

    [[menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/post/"
        weight = 10

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 20

[taxonomies]
  series = 'series'
  tag = 'tags'

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[module]
    [[module.imports]]
        path = "github.com/adityatelange/hugo-PaperMod"
